-- ============================================================================
--  EXPERT HARDWARE — fix expert_products.id sequence desync
-- ----------------------------------------------------------------------------
--  HOW TO RUN:
--    Supabase Dashboard -> SQL Editor -> New query -> paste this -> Run
--  Safe to re-run any time; only resets a counter, touches no data.
--
--  WHY THIS WAS NEEDED:
--  expert_products.id is `generated by default as identity (start with 100000)`.
--  At some point rows were inserted with an EXPLICIT id (the original 1-300
--  catalog seed, and the manual 301-320 batch that worked around this exact
--  bug by hand-assigning ids 100301-100320) instead of letting the identity
--  column auto-generate one. Postgres identity/serial sequences don't know
--  about explicit inserts — the sequence's internal counter never advances
--  when you bypass it — so its next auto-generated value can still collide
--  with an id a manual insert already used. That collision is what made the
--  admin's normal CSV-import button silently fail on new rows (23505 unique
--  violation on expert_products_pkey).
--
--  This bumps the sequence to continue past whatever the highest id actually
--  in use is right now, so every future insert (CSV import, Add Product)
--  auto-generates a safe, non-colliding id again — no more hand-assigning ids.
-- ============================================================================
select setval(
  pg_get_serial_sequence('public.expert_products', 'id'),
  (select coalesce(max(id), 100000) from public.expert_products),
  true
);

-- Verify: this should be higher than the highest id currently in the table.
-- select last_value from expert_products_id_seq;
