-- ============================================================================
--  EXPERT HARDWARE  —  Supabase setup
-- ----------------------------------------------------------------------------
--  Creates a DEDICATED set of  expert_*  tables for the Expert Hardware site.
--
--  IMPORTANT: This does NOT touch your  capslock_*  tables (that is your
--  separate PC-components store living in the same Supabase project). The two
--  stores stay completely independent.
--
--  HOW TO RUN:
--    Supabase Dashboard  ->  SQL Editor  ->  New query  ->  paste this  ->  Run
--  Safe to run more than once (uses IF NOT EXISTS / ON CONFLICT).
-- ============================================================================

-- 1) PRODUCTS  (admin-added products on top of the built-in catalogue)
--    Identity starts at 100000 so admin-added ids never collide with the
--    built-in catalogue ids that live in the website code.
create table if not exists public.expert_products (
  id         bigint generated by default as identity (start with 100000) primary key,
  name       text not null,
  category   text,
  price      numeric(10,3) default 0,
  img_url    text,
  hidden     boolean default false,
  created_at timestamptz default now()
);

-- 2) STOCK  (per-product stock status + quantity)
create table if not exists public.expert_stock (
  product_id bigint primary key,
  status     text default 'in-stock',
  qty        integer default 0
);

-- 3) PHOTOS  (base64 data-URL images, keyed by product id)
create table if not exists public.expert_photos (
  product_id bigint primary key,
  img_url    text
);

-- 4) HIDDEN  (products hidden from the storefront)
create table if not exists public.expert_hidden (
  product_id bigint primary key,
  hidden     boolean default true
);

-- 5) CATEGORY BACKGROUNDS  (custom category card images)
create table if not exists public.expert_cat_bgs (
  slug    text primary key,
  img_url text
);

-- 5b) SIDE BANNERS  (rotating brand banners next to the category grid — managed
--     from the admin Categories tab; the storefront splits brands evenly
--     between the two rotating banners)
create table if not exists public.expert_banners (
  id         bigint generated by default as identity primary key,
  brand      text not null,
  img_url    text not null,
  created_at timestamptz default now()
);

-- 6) SETTINGS  (key/value store; used for the "site temporarily closed" toggle)
create table if not exists public.expert_settings (
  key   text primary key,
  value text
);
insert into public.expert_settings (key, value)
values ('site_disabled', 'false')
on conflict (key) do nothing;

-- 7) ORDERS
create table if not exists public.expert_orders (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid,
  customer_name  text,
  customer_phone text,
  customer_email text,
  address        text,
  items          text,
  total          numeric(10,3) default 0,
  status         text default 'pending',
  notes          text,
  created_at     timestamptz default now()
);

-- 8) ANALYTICS  (views / searches per product)
create table if not exists public.expert_analytics (
  product_id bigint primary key,
  views      integer default 0,
  searches   integer default 0
);

-- 9) REVIEWS
create table if not exists public.expert_reviews (
  id         bigint generated by default as identity primary key,
  product_id bigint,
  name       text,
  rating     integer,
  comment    text,
  created_at timestamptz default now()
);

-- 10) CUSTOMERS  (profile row per signed-up account; id = auth user id)
create table if not exists public.expert_customers (
  id      uuid primary key,
  name    text,
  phone   text,
  address text
);

-- ============================================================================
--  ROW LEVEL SECURITY
--  The website talks to Supabase with the public "anon" key, so the storefront
--  tables need a policy that allows that. Customers are locked to their owner.
-- ============================================================================

-- Storefront tables: allow public (anon + signed-in) read/write.
do $$
declare t text;
begin
  foreach t in array array[
    'expert_products','expert_stock','expert_photos','expert_hidden',
    'expert_cat_bgs','expert_banners','expert_settings','expert_orders','expert_analytics',
    'expert_reviews'
  ]
  loop
    execute format('alter table public.%I enable row level security;', t);
    execute format('drop policy if exists %I on public.%I;', t || '_public_all', t);
    execute format(
      'create policy %I on public.%I for all to anon, authenticated using (true) with check (true);',
      t || '_public_all', t
    );
  end loop;
end $$;

-- Customers: each signed-in user can only see / edit their OWN profile row.
alter table public.expert_customers enable row level security;
drop policy if exists expert_customers_own on public.expert_customers;
create policy expert_customers_own
  on public.expert_customers
  for all
  to authenticated
  using  (auth.uid() = id)
  with check (auth.uid() = id);

-- ============================================================================
--  Done. Quick check — should list all 10 expert_ tables:
-- ============================================================================
-- select table_name from information_schema.tables
-- where table_schema = 'public' and table_name like 'expert_%'
-- order by table_name;

-- ============================================================================
--  ANALYTICS INCREMENT FUNCTION
--  Called by the storefront (rpc/increment_expert_analytics) to bump a
--  product's view/search counters. Dedicated name so it never clashes with
--  the PC store's own analytics.
-- ============================================================================
create or replace function public.increment_expert_analytics(
  p_id bigint, p_views integer, p_searches integer
) returns void
language sql
as $func$
  insert into public.expert_analytics (product_id, views, searches)
  values (p_id, coalesce(p_views,0), coalesce(p_searches,0))
  on conflict (product_id) do update
    set views    = public.expert_analytics.views    + coalesce(excluded.views, 0),
        searches = public.expert_analytics.searches + coalesce(excluded.searches, 0);
$func$;

grant execute on function public.increment_expert_analytics(bigint, integer, integer)
  to anon, authenticated;
